### ISSUE TITLE
Bad admin account

### ISSUE THREAD

**Issue by jchevelu** [YunoHost-Apps/gitlab_ynh#240]
### Describe the bug

When installing gitlab for Yunohost, the administrator is not set to the correct user but an empty account (root/Administrator/administrator@exemple.com)

### Context

- Hardware: VPS
- YunoHost version: 11.2.10
- Gitlab : 16.8.1~ynh1
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:  yes
- Using, or trying to install package version/branch: default install

### Steps to reproduce

- In YunoHost web interface
   1. Go to admin panel
   2. Applications
   3. Install
   4. Gitlab
   5. Admin user -> any YunoHost user in the LDAP (eg. myadmin)
   6. log with this user and see he is not administrator. 
   7. search for other users, you should see an other user named Administrator (root)

### Expected behavior

The user "myadmin" should be administrator. not the "Administrator/root" user.

### Notes

3 weeks ago, when I installed another server using the same procedure, the problem did not occurred (before the security update). 

### Workaround

If someone is looking for a temporary solution.
After installation, run in ssh as root user:
```bash
gitlab-rails console -e production
```
when the console is available (it was very slow for me, like 40s):

```bash
user = User.find_by(username: 'myadmin')
user.admin = true
user.save!
exit
```

**Comment by haydenwalker980** [comment]
projects like GitLab usually include something like user controls in a rake task, i'll see if there is one

**Comment by haydenwalker980** [comment]
no rake task, however:

rails has a "runner" option (https://guides.rubyonrails.org/command_line.html#bin-rails-runner) which lets you run this via a command line

i'll do some testing with this before anything

**Comment by haydenwalker980** [comment]
actually:

https://github.com/YunoHost-Apps/gitlab_ynh/blob/master/scripts/install#L138

seems like theres a missing exclamation.

`.save` hasn't been recommended since 5.2.3, 16.8.1 which is latest stable uses 7.0.8, i'll see if i can fix this with a PR

**Comment by kay0u** [comment]
Should be fixed in 16.9.0, feel free to reopen this issue if needed

**Comment by samiy803** [comment]
Still happening on 16.9.1

**Comment by haydenwalker980** [comment]
yeah just tested and it's still happening for some odd reason. I'll look further into it

**Comment by kay0u** [comment]
should be fixed by https://github.com/YunoHost-Apps/gitlab_ynh/pull/249

Please reopen if needed
