### ISSUE TITLE
Git over HTTPS not working after upgrade to Yunohost 12

### ISSUE THREAD

**Issue by philippstappert** [YunoHost-Apps/gitlab_ynh#269]
### Describe the bug

After upgrading to YunoHost 12, i always get those errors when trying to authenticate to Git over HTTPS:

```
remote: HTTP Basic: Access denied. If a password was provided for Git authentication, the password was incorrect or you're required to use a token instead of a password. If a token was provided, it was either incorrect, expired, or improperly scoped. See https://git.myurl.de/help/topics/git/troubleshooting_git.md#error-on-git-fetch-http-basic-access-denied
```

But the tokens are all still valid, after creating new ones, the problem persists.

### Context

- Hardware: VPS bought online
- YunoHost version: 12.0.7
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Just create a personal access token and try to use it to clone a repo on GitLab. It just doesn't work. Same problem with CI/CD: It also produces the same error.

### Expected behavior

Cloning, pushing, pulling works (authentication doesn't return this error.

### Logs

found none matching to those requests / problems as there are hundreds of log files for gitlab, if you need a specific one feel free to comment and i try to find it :)

**Comment by philippstappert** [comment]
Current workaround: Using SSH-Keys. But CI/CD just doesn't work anymore which is really annoying

**Comment by philippstappert** [comment]
hmh, seems to be related to #267

**Comment by kay0u** [comment]
Should be fixed by https://github.com/YunoHost-Apps/gitlab_ynh/pull/268

**Comment by kegalo** [comment]
both this and #267 still occur, i just ran a ci job that couldn't pull my private repo
